package com.shaw.lts.persist.mapper;

import com.shaw.lts.persist.BaseMapper;
import com.shaw.lts.persist.model.LtsSysUser;

/**
 * @author This class was generated by MyBatis Generator.
 */
public interface LtsSysUserMapper extends BaseMapper<LtsSysUser> {
}