package com.shaw.lts.persist.mapper;

import com.shaw.lts.persist.BaseMapper;
import com.shaw.lts.persist.model.SysHandleLog;

/**
 * @author This class was generated by MyBatis Generator.
 */
public interface SysHandleLogMapper extends BaseMapper<SysHandleLog> {
}