package com.shaw.lts.persist.model;

import java.io.Serializable;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Database Table Remarks:
 *   lts_sys_user
 * @author This class was generated by MyBatis Generator.
 */
@Table(name = "lts_sys_user")
public class LtsSysUser implements Serializable {
    /**
     * 主键
     */
    @Id
    private Long id;

    /**
     * 用户id
     */
    @Column(name = "user_id")
    private String userId;

    /**
     * 登录名(手机号)
     */
    @Column(name = "login_name")
    private String loginName;

    /**
     * 登录密码
     */
    @Column(name = "login_password")
    private String loginPassword;

    /**
     * 用户名
     */
    @Column(name = "user_name")
    private String userName;

    /**
     * 是否vip
     */
    @Column(name = "bln_vip")
    private String blnVip;

    /**
     * vip过期时间
     */
    @Column(name = "vip_expire_time")
    private Date vipExpireTime;

    /**
     * 是否启用
     */
    @Column(name = "bln_enable")
    private String blnEnable;

    /**
     * 是否锁定
     */
    @Column(name = "bln_lock")
    private String blnLock;

    /**
     * 是否在线
     */
    @Column(name = "bln_online")
    private String blnOnline;

    /**
     * 是否删除
     */
    @Column(name = "bln_delete")
    private String blnDelete;

    /**
     * 头像地址
     */
    @Column(name = "avatar_url")
    private String avatarUrl;

    /**
     * 备注
     */
    private String remarks;

    /**
     * 创建时间
     */
    @Column(name = "create_time")
    private Date createTime;

    /**
     * 更新时间
     */
    @Column(name = "update_time")
    private Date updateTime;

    private static final long serialVersionUID = 1L;

    /**
     * 获取主键
     *
     * @return id - 主键
     */
    public Long getId() {
        return id;
    }

    /**
     * 设置主键
     *
     * @param id 主键
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * 获取用户id
     *
     * @return user_id - 用户id
     */
    public String getUserId() {
        return userId;
    }

    /**
     * 设置用户id
     *
     * @param userId 用户id
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * 获取登录名(手机号)
     *
     * @return login_name - 登录名(手机号)
     */
    public String getLoginName() {
        return loginName;
    }

    /**
     * 设置登录名(手机号)
     *
     * @param loginName 登录名(手机号)
     */
    public void setLoginName(String loginName) {
        this.loginName = loginName;
    }

    /**
     * 获取登录密码
     *
     * @return login_password - 登录密码
     */
    public String getLoginPassword() {
        return loginPassword;
    }

    /**
     * 设置登录密码
     *
     * @param loginPassword 登录密码
     */
    public void setLoginPassword(String loginPassword) {
        this.loginPassword = loginPassword;
    }

    /**
     * 获取用户名
     *
     * @return user_name - 用户名
     */
    public String getUserName() {
        return userName;
    }

    /**
     * 设置用户名
     *
     * @param userName 用户名
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * 获取是否vip
     *
     * @return bln_vip - 是否vip
     */
    public String getBlnVip() {
        return blnVip;
    }

    /**
     * 设置是否vip
     *
     * @param blnVip 是否vip
     */
    public void setBlnVip(String blnVip) {
        this.blnVip = blnVip;
    }

    /**
     * 获取vip过期时间
     *
     * @return vip_expire_time - vip过期时间
     */
    public Date getVipExpireTime() {
        return vipExpireTime;
    }

    /**
     * 设置vip过期时间
     *
     * @param vipExpireTime vip过期时间
     */
    public void setVipExpireTime(Date vipExpireTime) {
        this.vipExpireTime = vipExpireTime;
    }

    /**
     * 获取是否启用
     *
     * @return bln_enable - 是否启用
     */
    public String getBlnEnable() {
        return blnEnable;
    }

    /**
     * 设置是否启用
     *
     * @param blnEnable 是否启用
     */
    public void setBlnEnable(String blnEnable) {
        this.blnEnable = blnEnable;
    }

    /**
     * 获取是否锁定
     *
     * @return bln_lock - 是否锁定
     */
    public String getBlnLock() {
        return blnLock;
    }

    /**
     * 设置是否锁定
     *
     * @param blnLock 是否锁定
     */
    public void setBlnLock(String blnLock) {
        this.blnLock = blnLock;
    }

    /**
     * 获取是否在线
     *
     * @return bln_online - 是否在线
     */
    public String getBlnOnline() {
        return blnOnline;
    }

    /**
     * 设置是否在线
     *
     * @param blnOnline 是否在线
     */
    public void setBlnOnline(String blnOnline) {
        this.blnOnline = blnOnline;
    }

    /**
     * 获取是否删除
     *
     * @return bln_delete - 是否删除
     */
    public String getBlnDelete() {
        return blnDelete;
    }

    /**
     * 设置是否删除
     *
     * @param blnDelete 是否删除
     */
    public void setBlnDelete(String blnDelete) {
        this.blnDelete = blnDelete;
    }

    /**
     * 获取头像地址
     *
     * @return avatar_url - 头像地址
     */
    public String getAvatarUrl() {
        return avatarUrl;
    }

    /**
     * 设置头像地址
     *
     * @param avatarUrl 头像地址
     */
    public void setAvatarUrl(String avatarUrl) {
        this.avatarUrl = avatarUrl;
    }

    /**
     * 获取备注
     *
     * @return remarks - 备注
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * 设置备注
     *
     * @param remarks 备注
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    /**
     * 获取创建时间
     *
     * @return create_time - 创建时间
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * 设置创建时间
     *
     * @param createTime 创建时间
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * 获取更新时间
     *
     * @return update_time - 更新时间
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * 设置更新时间
     *
     * @param updateTime 更新时间
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}