package com.shaw.lts.persist.model;

import java.io.Serializable;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Database Table Remarks:
 *   lts_user_track
 * @author This class was generated by MyBatis Generator.
 */
@Table(name = "lts_user_track")
public class LtsUserTrack implements Serializable {
    /**
     * 主键
     */
    @Id
    private Long id;

    /**
     * 用户id
     */
    @Column(name = "user_id")
    private String userId;

    /**
     * 经度
     */
    private Double longitude;

    /**
     * 纬度
     */
    private Double latitude;

    /**
     * 海拔
     */
    private Double altitude;

    /**
     * 当前地址
     */
    @Column(name = "track_address")
    private String trackAddress;

    /**
     * 移动方向
     */
    private Float direction;

    /**
     * 位置精度
     */
    private Float accuracy;

    /**
     * 在此时间
     */
    @Column(name = "track_time")
    private Date trackTime;

    /**
     * 备注
     */
    private String remarks;

    /**
     * 创建时间
     */
    @Column(name = "create_time")
    private Date createTime;

    /**
     * 更新时间
     */
    @Column(name = "update_time")
    private Date updateTime;

    private static final long serialVersionUID = 1L;

    /**
     * 获取主键
     *
     * @return id - 主键
     */
    public Long getId() {
        return id;
    }

    /**
     * 设置主键
     *
     * @param id 主键
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * 获取用户id
     *
     * @return user_id - 用户id
     */
    public String getUserId() {
        return userId;
    }

    /**
     * 设置用户id
     *
     * @param userId 用户id
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * 获取经度
     *
     * @return longitude - 经度
     */
    public Double getLongitude() {
        return longitude;
    }

    /**
     * 设置经度
     *
     * @param longitude 经度
     */
    public void setLongitude(Double longitude) {
        this.longitude = longitude;
    }

    /**
     * 获取纬度
     *
     * @return latitude - 纬度
     */
    public Double getLatitude() {
        return latitude;
    }

    /**
     * 设置纬度
     *
     * @param latitude 纬度
     */
    public void setLatitude(Double latitude) {
        this.latitude = latitude;
    }

    /**
     * 获取海拔
     *
     * @return altitude - 海拔
     */
    public Double getAltitude() {
        return altitude;
    }

    /**
     * 设置海拔
     *
     * @param altitude 海拔
     */
    public void setAltitude(Double altitude) {
        this.altitude = altitude;
    }

    /**
     * 获取当前地址
     *
     * @return track_address - 当前地址
     */
    public String getTrackAddress() {
        return trackAddress;
    }

    /**
     * 设置当前地址
     *
     * @param trackAddress 当前地址
     */
    public void setTrackAddress(String trackAddress) {
        this.trackAddress = trackAddress;
    }

    /**
     * 获取移动方向
     *
     * @return direction - 移动方向
     */
    public Float getDirection() {
        return direction;
    }

    /**
     * 设置移动方向
     *
     * @param direction 移动方向
     */
    public void setDirection(Float direction) {
        this.direction = direction;
    }

    /**
     * 获取位置精度
     *
     * @return accuracy - 位置精度
     */
    public Float getAccuracy() {
        return accuracy;
    }

    /**
     * 设置位置精度
     *
     * @param accuracy 位置精度
     */
    public void setAccuracy(Float accuracy) {
        this.accuracy = accuracy;
    }

    /**
     * 获取在此时间
     *
     * @return track_time - 在此时间
     */
    public Date getTrackTime() {
        return trackTime;
    }

    /**
     * 设置在此时间
     *
     * @param trackTime 在此时间
     */
    public void setTrackTime(Date trackTime) {
        this.trackTime = trackTime;
    }

    /**
     * 获取备注
     *
     * @return remarks - 备注
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * 设置备注
     *
     * @param remarks 备注
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    /**
     * 获取创建时间
     *
     * @return create_time - 创建时间
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * 设置创建时间
     *
     * @param createTime 创建时间
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * 获取更新时间
     *
     * @return update_time - 更新时间
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * 设置更新时间
     *
     * @param updateTime 更新时间
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}