package com.shaw.lts.persist.model;

import java.io.Serializable;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Database Table Remarks:
 *   sys_handle_log
 * @author This class was generated by MyBatis Generator.
 */
@Table(name = "sys_handle_log")
public class SysHandleLog implements Serializable {
    /**
     * 主键
     */
    @Id
    private Long id;

    /**
     * 日志追踪 ID
     */
    @Column(name = "trace_id")
    private String traceId;

    /**
     * 操作模块
     */
    private String title;

    /**
     * 处理业务类型
     */
    @Column(name = "business_type")
    private String businessType;

    /**
     * 请求方法
     */
    private String method;

    /**
     * 请求方式
     */
    @Column(name = "request_type")
    private String requestType;

    /**
     * 处理日期
     */
    @Column(name = "handle_date")
    private String handleDate;

    /**
     * 登录用户
     */
    @Column(name = "login_name")
    private String loginName;

    /**
     * 用户名
     */
    @Column(name = "user_name")
    private String userName;

    /**
     * 请求ip
     */
    @Column(name = "request_ip")
    private String requestIp;

    /**
     * 请求地址
     */
    @Column(name = "request_url")
    private String requestUrl;

    /**
     * 请求开始时间
     */
    @Column(name = "request_start_time")
    private String requestStartTime;

    /**
     * 请求结束时间
     */
    @Column(name = "request_end_time")
    private String requestEndTime;

    /**
     * 请求耗时(毫秒)
     */
    @Column(name = "request_expand_time")
    private Long requestExpandTime;

    /**
     * 是否处理成功
     */
    @Column(name = "bln_success")
    private String blnSuccess;

    /**
     * 创建时间
     */
    @Column(name = "create_time")
    private Date createTime;

    /**
     * 更新时间
     */
    @Column(name = "update_time")
    private Date updateTime;

    /**
     * 错误描述
     */
    @Column(name = "error_desc")
    private String errorDesc;

    /**
     * 请求参数
     */
    @Column(name = "request_param")
    private String requestParam;

    /**
     * 响应参数
     */
    @Column(name = "response_param")
    private String responseParam;

    private static final long serialVersionUID = 1L;

    /**
     * 获取主键
     *
     * @return id - 主键
     */
    public Long getId() {
        return id;
    }

    /**
     * 设置主键
     *
     * @param id 主键
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * 获取日志追踪 ID
     *
     * @return trace_id - 日志追踪 ID
     */
    public String getTraceId() {
        return traceId;
    }

    /**
     * 设置日志追踪 ID
     *
     * @param traceId 日志追踪 ID
     */
    public void setTraceId(String traceId) {
        this.traceId = traceId;
    }

    /**
     * 获取操作模块
     *
     * @return title - 操作模块
     */
    public String getTitle() {
        return title;
    }

    /**
     * 设置操作模块
     *
     * @param title 操作模块
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * 获取处理业务类型
     *
     * @return business_type - 处理业务类型
     */
    public String getBusinessType() {
        return businessType;
    }

    /**
     * 设置处理业务类型
     *
     * @param businessType 处理业务类型
     */
    public void setBusinessType(String businessType) {
        this.businessType = businessType;
    }

    /**
     * 获取请求方法
     *
     * @return method - 请求方法
     */
    public String getMethod() {
        return method;
    }

    /**
     * 设置请求方法
     *
     * @param method 请求方法
     */
    public void setMethod(String method) {
        this.method = method;
    }

    /**
     * 获取请求方式
     *
     * @return request_type - 请求方式
     */
    public String getRequestType() {
        return requestType;
    }

    /**
     * 设置请求方式
     *
     * @param requestType 请求方式
     */
    public void setRequestType(String requestType) {
        this.requestType = requestType;
    }

    /**
     * 获取处理日期
     *
     * @return handle_date - 处理日期
     */
    public String getHandleDate() {
        return handleDate;
    }

    /**
     * 设置处理日期
     *
     * @param handleDate 处理日期
     */
    public void setHandleDate(String handleDate) {
        this.handleDate = handleDate;
    }

    /**
     * 获取登录用户
     *
     * @return login_name - 登录用户
     */
    public String getLoginName() {
        return loginName;
    }

    /**
     * 设置登录用户
     *
     * @param loginName 登录用户
     */
    public void setLoginName(String loginName) {
        this.loginName = loginName;
    }

    /**
     * 获取用户名
     *
     * @return user_name - 用户名
     */
    public String getUserName() {
        return userName;
    }

    /**
     * 设置用户名
     *
     * @param userName 用户名
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * 获取请求ip
     *
     * @return request_ip - 请求ip
     */
    public String getRequestIp() {
        return requestIp;
    }

    /**
     * 设置请求ip
     *
     * @param requestIp 请求ip
     */
    public void setRequestIp(String requestIp) {
        this.requestIp = requestIp;
    }

    /**
     * 获取请求地址
     *
     * @return request_url - 请求地址
     */
    public String getRequestUrl() {
        return requestUrl;
    }

    /**
     * 设置请求地址
     *
     * @param requestUrl 请求地址
     */
    public void setRequestUrl(String requestUrl) {
        this.requestUrl = requestUrl;
    }

    /**
     * 获取请求开始时间
     *
     * @return request_start_time - 请求开始时间
     */
    public String getRequestStartTime() {
        return requestStartTime;
    }

    /**
     * 设置请求开始时间
     *
     * @param requestStartTime 请求开始时间
     */
    public void setRequestStartTime(String requestStartTime) {
        this.requestStartTime = requestStartTime;
    }

    /**
     * 获取请求结束时间
     *
     * @return request_end_time - 请求结束时间
     */
    public String getRequestEndTime() {
        return requestEndTime;
    }

    /**
     * 设置请求结束时间
     *
     * @param requestEndTime 请求结束时间
     */
    public void setRequestEndTime(String requestEndTime) {
        this.requestEndTime = requestEndTime;
    }

    /**
     * 获取请求耗时(毫秒)
     *
     * @return request_expand_time - 请求耗时(毫秒)
     */
    public Long getRequestExpandTime() {
        return requestExpandTime;
    }

    /**
     * 设置请求耗时(毫秒)
     *
     * @param requestExpandTime 请求耗时(毫秒)
     */
    public void setRequestExpandTime(Long requestExpandTime) {
        this.requestExpandTime = requestExpandTime;
    }

    /**
     * 获取是否处理成功
     *
     * @return bln_success - 是否处理成功
     */
    public String getBlnSuccess() {
        return blnSuccess;
    }

    /**
     * 设置是否处理成功
     *
     * @param blnSuccess 是否处理成功
     */
    public void setBlnSuccess(String blnSuccess) {
        this.blnSuccess = blnSuccess;
    }

    /**
     * 获取创建时间
     *
     * @return create_time - 创建时间
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * 设置创建时间
     *
     * @param createTime 创建时间
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * 获取更新时间
     *
     * @return update_time - 更新时间
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * 设置更新时间
     *
     * @param updateTime 更新时间
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * 获取错误描述
     *
     * @return error_desc - 错误描述
     */
    public String getErrorDesc() {
        return errorDesc;
    }

    /**
     * 设置错误描述
     *
     * @param errorDesc 错误描述
     */
    public void setErrorDesc(String errorDesc) {
        this.errorDesc = errorDesc;
    }

    /**
     * 获取请求参数
     *
     * @return request_param - 请求参数
     */
    public String getRequestParam() {
        return requestParam;
    }

    /**
     * 设置请求参数
     *
     * @param requestParam 请求参数
     */
    public void setRequestParam(String requestParam) {
        this.requestParam = requestParam;
    }

    /**
     * 获取响应参数
     *
     * @return response_param - 响应参数
     */
    public String getResponseParam() {
        return responseParam;
    }

    /**
     * 设置响应参数
     *
     * @param responseParam 响应参数
     */
    public void setResponseParam(String responseParam) {
        this.responseParam = responseParam;
    }
}